version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DBHOST}
      - DB_PORT=${DBPORT}
      - DB_USER=${DBUSER}
      - DB_PASSWORD=${DBPASSWORD}
      - DB_NAME=${DBNAME}
    depends_on:
      - postgres
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"
    volumes:
      - /postgres-data:/var/lib/postgresql/data

